#!/usr/bin/env bash
#SBATCH -A NAISS2024-22-1419 -p alvis
#SBATCH -N 1 --gpus-per-node=V100:1  # We're launching 2 nodes with 4 Nvidia T4 GPUs each
#SBATCH -t 0-00:15:00

#module load TensorFlow/2.5.0-fosscuda-2020b
#pwd
#ls
#python app.py

module load virtualenv/20.23.1-GCCcore-12.3.0 matplotlib/3.7.2-gfbf-2023a SciPy-bundle/2023.07-gfbf-2023a
module load PyTorch/1.12.0-foss-2022a-CUDA-11.7.0
#source ../../torch_test/bin/activate

echo Test tesnorflow
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
# python src/main_laplacian.py --batch_size 12 --lr 0.00000352 --lr_warmup 1000 --n_epochs 15 --lambda_a 0.0 --lambda_w 10.0 --device "cuda:0" --data senate --pb_refresh 30.0 --partition True --base_model "trained/bert-pretrained-3b"
