"""
Convert a CSV file generated by Cmdstanpy to a folder of pwe.Embedding files
"""
import numpy as np
import cmdstanpy
import pickle, json
from trainerlog import get_logger
LOGGER = get_logger("conversion")
from probabilistic_word_embeddings.embeddings import Embedding
from pathlib import Path
import pandas as pd
import tqdm
from hashlib import md5

def string_hash(string):
    return md5(string.encode()).hexdigest()

def remove_raw_vectors(df, cols=None):
    if cols is None:
        cols = [col for col in df.columns if "_raw" not in col]
    else:
        assert len(cols) == len(df.columns)
        print("COLUMNS: (TRUE; REF)")
        print(cols[:25])
        print(df.columns[:25])
        cols = [col for (col, ref) in zip(df.columns, cols) if "_raw" not in ref]
    return df[cols]

def main(args):
    df = None
    cols = pd.read_csv(args.path, comment="#", nrows=2).columns

    if args.chunks is not None:
        LOGGER.info("Split into chunks...")
        df = pd.read_csv(args.path, comment="#", header=None, nrows=args.chunks)
        df = remove_raw_vectors(df, cols=cols)
    else:
        df = pd.read_csv(args.path, comment="#", header=None)
        df = remove_raw_vectors(df, cols=cols)
    print(df)

    x = df.loc[0].to_numpy()
    print(x)
    print(x.shape)
    print(x[:15])

    first_index = 7
    assert "word" not in x[first_index - 1], f"{x[first_index - 1]} should be metadata"
    assert "word" in x[first_index], f"{x[first_index - 1]} should not be metadata"

    x = x[first_index:]
    print(x.shape)

    K = max([int(elem.split(".")[-1]) for elem in x])
    print("dim (K)", K)
    V = max([int(elem.split(".")[-2]) for elem in x])
    print("V", V)

    rho = np.reshape(x[:K*V], (K, V))
    print(rho[:, 0])
    print(rho[:, -1])

    alpha = np.reshape(x[K*V:], (K, V))
    print(alpha[:, 0])
    print(alpha[:, -1])

    #exit()
    LOGGER.info(f"Convert to pwe.Embedding...")
    outfolder = args.outpath
    if args.outpath is None:
        dfhash = sorted([str(elem) for elem in df.loc[1:, 0]])
        print(dfhash)
        dfhash = string_hash("".join(dfhash))
        print(dfhash)
        print("HASH", dfhash)
        random_nums = dfhash[:6]
        outfolder = f"cmdstanpy-K{K}-V{V}-embedding-{random_nums}"

    outfolder = Path(outfolder)
    LOGGER.info(f"Output folder {outfolder}...")

    vocab = None
    if args.vocabulary is None:
        LOGGER.info(f"Create simulation vocabulary: (word0, word1, ..., wordV)")
        vocab = sorted([f"word{ix}" for ix in range(V)])
        print(" ".join(vocab))
    else:
        LOGGER.info(f"Load vocabulary from file {args.vocabulary}")
        with open(args.vocabulary, "r") as f:
            datafile = json.load(f)

        vocab_dict = bidict.bidict(datafile["vocabulary"])
        vocab = sorted([(a,b) for a,b in vocab_dict.items()], key=lambda x: x[1])
        vocab = [a for a,b in vocab]

    vocab_c = [f"{wd}_c" for wd in vocab]
    LOGGER.debug(f"Vocabulary: {vocab}")

    samples = len(df) - 1
    LOGGER.info(f"V: {V}, K: {K}, samples: {samples}")
    done, r = False, 0

    while not done and args.chunks is not None:        
        if args.chunks is not None:
            df = pd.read_csv(args.path, comment="#", header=None, skiprows=r * args.chunks, nrows=args.chunks)
            df = remove_raw_vectors(df, cols=cols)

        samples = len(df) - 1
        LOGGER.info(f"V: {V}, K: {K}, samples: {samples}, r: {r}")

        for sample_ix in tqdm.tqdm(list(range(samples))):
            x = df.loc[sample_ix + 1].to_numpy()
            x = x[first_index:]
            x = [float(elem) for elem in x]
            rho = np.reshape(x[:K*V], (K, V))
            print(rho[:, 0])
            print(rho[:, -1])
            alpha = np.reshape(x[K*V:], (K, V))

            e = Embedding(set(vocab), dimensionality=K)
            print(rho.shape)
            print(rho.dtype)
            print(alpha.shape)
            e[vocab] = rho.T
            e[vocab_c] = alpha.T

            LOGGER.info(f"K: {e.dimensionality}")
            outpath = outfolder / f"sample-{sample_ix}.pkl"
            outfolder.mkdir(exist_ok=True)
            LOGGER.info(f"Save to {outpath}...")
            e.save(str(outpath.absolute()))

        done = args.chunks is None
        r += 1

if __name__ == "__main__":
    import argparse
    argparser = argparse.ArgumentParser(description=__doc__)
    argparser.add_argument("--path", type=str, required=True, help="Path to the stan fit file")
    argparser.add_argument("--vocabulary", type=str, default=None)
    argparser.add_argument("--outpath", type=str, default=None, help="Path to the output folder; optional")
    argparser.add_argument("--chunks", type=int, default=None, help="Split CSV for chunks of this size to limit memory footprint")
    args = argparser.parse_args()
    print(args)
    main(args)
